# Generated by Django 3.1 on 2020-08-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='profile_pics')),
                ('bio', models.TextField()),
                ('tech_stack', models.CharField(choices=[('Python', 'Python'), ('Javascript', 'JavaScript'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('C++', 'C++'), ('C#', 'C#'), ('C', 'C'), ('Java', 'Java')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
