# Generated by Django 3.1 on 2020-08-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200820_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='likeability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.ManyToManyField(null=True, to='users.Technology'),
        ),
    ]
