# Generated by Django 3.1 on 2020-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200821_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.ManyToManyField(to='users.Technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
