# Generated by Django 3.1 on 2020-08-21 11:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200821_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tech_stacks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript')], max_length=31, null=True),
        ),
    ]
