# Generated by Django 3.1 on 2020-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200821_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, to='users.Technology'),
        ),
    ]
