# Generated by Django 3.1 on 2020-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200821_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tech_stacks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
