# Generated by Django 3.1 on 2020-08-23 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0032_auto_20200823_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_by',
            field=models.ManyToManyField(related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
