# Generated by Django 3.1 on 2020-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('Linux', 'Linux')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
