# Generated by Django 3.1 on 2020-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20200827_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spacing',
            field=models.CharField(blank=True, choices=[('Tabs', 'Tabs'), ('Spaces', 'Spaces')], default=None, max_length=10, null=True),
        ),
    ]
