# Generated by Django 3.1 on 2020-08-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200824_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], max_length=100, null=True),
        ),
    ]
