# Generated by Django 3.1 on 2020-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200824_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[(1, 'Read'), (2, 'Unread')], default=2, max_length=100, null=True),
        ),
    ]
