# Generated by Django 3.1 on 2020-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200824_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Read', max_length=100, null=True),
        ),
    ]
